services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    container_name: python-flask
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: redis
    ports: 
      - "6379:6379"
